# Generated by Django 5.1.1 on 2024-12-08 01:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ventas', '0004_venta_total'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='venta',
            name='total',
        ),
    ]
