# Generated by Django 5.1.1 on 2024-12-09 05:00

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('consulta', '0002_remove_inventariosucursal_stock'),
        ('ventas', '0006_venta_precio_total'),
    ]

    operations = [
        migrations.AddField(
            model_name='venta',
            name='sucursal',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='consulta.sucursal'),
        ),
    ]
